spring:
  application:
    name: utility-api
  devtools:
    livereload:
      enabled: true
    restart:
      trigger-file: restart-trigger
server:
  servlet:
    context-path: /utility-api
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include:
        - mappings
        - info
        - health
        - config
        - actuator
zipcode:
  serviceURL: http://postalpincode.in/api/pincode/%d